[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.12"